project: "Week4_MobileNetV2"
entity: "c3-team4"
experiment_name: "MobileNetV2_Halved"

data:
  train_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/train"
  test_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/test"
  img_size: 256
  batch_size: 32
  num_workers: 4
  val_split: 0.5
  num_classes: 8

model:
  name: "MobileNet"
  params:
    version: "v2"
    alpha: 1.0
    v2_spec:
      - [32, 2]  # First regular convolution
      - [16, 1, 1]  # Block of depthwise convolutions
      - [24, 2, 6]
      - [24, 1, 6]
      - [32, 2, 6]
      - [32, 1, 6]
      - [64, 2, 6]
      - [64, 1, 6]
      - [96, 2, 6]
      - [96, 1, 6]


training:
  epochs: 500  # Standardizing to 500 for all models
  learning_rate: 0.001
  seed: 42
  optimizer: "adam"
  criterion: "crossentropy"
