program: main.py
method: grid
name: Sweep_Distill_Multi_Arch
project: Week4_ShuffleNet_Sweep
entity: c3-team4

metric:
  name: best_test_accuracy
  goal: maximize

parameters:
  config:
    value: configs/shufflenet/shufflenet_distill.yaml
  
  # Distillation Hyperparameters
  distillation.temperature:
    values: [2.0, 4.0, 6.0, 8.0]
  distillation.alpha:
    values: [0.3, 0.5, 0.7, 0.9, 1]
    
  # Model Variants (Architectures)
  student_model.params:
    values:
      # ShuffleNet_Nano
      - {stages_repeats: [2, 2, 2], stages_out_channels: [12, 16, 24, 32, 32], experiment_name: "ShuffleNet_Nano"}
      
      # ShuffleNet_Femto_1x
      - {stages_repeats: [1, 1, 1], stages_out_channels: [4, 8, 12, 16, 16], experiment_name: "ShuffleNet_Femto_1x"}
      
      # ShuffleNet_Atto
      - {stages_repeats: [2, 2, 2], stages_out_channels: [4, 4, 6, 8, 8], experiment_name: "ShuffleNet_Atto"}
      
      # ShuffleNet_Atto_1x
      - {stages_repeats: [1, 1, 1], stages_out_channels: [4, 4, 6, 8, 8], experiment_name: "ShuffleNet_Atto_1x"}
