project: "Week4_MobileNet"
entity: "c3-team4"
experiment_name: "MobileNet_WithoutStage_Thin"

data:
  train_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/train"
  test_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/test"
  img_size: 256
  batch_size: 32
  num_workers: 4
  val_split: 0.5
  num_classes: 8

model:
  name: "MobileNet"
  params:
    out_channels:
      - [3, 2]  # First regular convolution
      - [6, 1]  # Block of depthwise convolutions
      - [12, 2]
      - [12, 1]
      - [24, 2]
      - [24, 1]
      - [30, 2]
      - [30, 1]
      - [50, 2]
      - [50, 1]


training:
  epochs: 500  # Standardizing to 500 for all models
  learning_rate: 0.001
  seed: 42
  optimizer: "adam"
  criterion: "crossentropy"
