project: "Week4_MobileNet"
entity: "c3-team4"
experiment_name: "0.25MobileNet_WithoutStage"

data:
  train_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/train"
  test_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/test"
  img_size: 256
  batch_size: 32
  num_workers: 4
  val_split: 0.5
  num_classes: 8

model:
  name: "MobileNet"
  params:
    out_channels:
      - [32, 2]  # First regular convolution
      - [64, 1]  # Block of depthwise convolutions
      - [128, 2]
      - [128, 1]
      - [256, 2]
      - [256, 1]
      - [512, 2]
      - [512, 1]
      - [1024, 2]
      - [1024, 1]
    alpha: 0.25


training:
  epochs: 500  # Standardizing to 500 for all models
  learning_rate: 0.001
  seed: 42
  optimizer: "adam"
  criterion: "crossentropy"
