experiment_name: "ExperimentalNet_prueba"
project: "Week4_Experimental_Sweep"
entity: "c3-team4"

data:
  train_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/train"
  test_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/test"
  img_size: &IMG_SIZE 256
  batch_size: 32
  num_workers: 4
  num_classes: 8

model:
  name: "ExperimentalCNN"
  params:
    channels: [32, 32, 32, 32, 32, 32]
    img_size: *IMG_SIZE
    dropout: 0.0
    use_gap: false
    use_bottleneck: false
    use_attention: false
    use_residual: false
    use_bn: true

training:
  epochs: 50
  learning_rate: 0.001
  optimizer: "adam"  
  criterion: "crossentropy"
  seed: 42