experiment_name: "SqueezeNet"
project: week4-init
entity: c3-team4

# Modular parameters
data:
  train_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/train"
  test_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/test"
  img_size: 224
  batch_size: 32
  num_workers: 4
  num_classes: 8

model:
  name: "SqueezeNet"
  feature_extraction: true

training:
  epochs: 20
  learning_rate: 0.0001
  optimizer: "adam"  
  criterion: "crossentropy"
  seed: 42