project: "Week4_ShuffleNet"
experiment_name: "ShuffleNet_Big"

data:
  train_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/train"
  test_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/test"
  img_size: 64
  batch_size: 32
  num_workers: 4
  val_split: 0.5

model:
  name: "ShuffleNetMini"
  stages_repeats: [4, 8, 4]
  stages_out_channels: [24, 116, 232, 464, 1024]
  dropout: 0.2

training:
  epochs: 100
  learning_rate: 0.001
  seed: 42
  optimizer: "adam"
