project: week3-hyperparameter-optimization
entity: c3-team4
program: main_hyp.py
method: bayes # random, grid, bayes
metric:
  name: test_accuracy
  goal: maximize
parameters:
  batch_size:
    values: [10, 20, 40, 60, 80, 100]
  lr:
    values: [0.0001, 0.001, 0.01, 0.1, 0.2, 0.3]
  optimizer:
    values: ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam']
  momentum:
    values: [0.0, 0.2, 0.4, 0.6, 0.8, 0.9]
  decay:
    values: [0, 1e-5, 1e-6, 1e-7]
  scheduler:
    values: ['StepLR', 'ReduceLROnPlateau', 'LinearLR', 'CosineAnnealingLR']
  epochs:
    values: [10, 20, 50, 100]
  data_augmentation:
    values: [True, False]
  dropout:
    values: [0.1, 0.3, 0.5, 0.7]
  unfreeze_depth:
    values: [2] #[0, 1, 2, 3]
  activation:
    values: ['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'leakyrelu']

