program: main.py
method: grid
name: Sweep_Distill_Multi_Arch
project: Week4_MobileNet_Sweep
entity: c3-team4

metric:
  name: best_test_accuracy
  goal: maximize

parameters:
  config:
    value: configs/mobilenet/mobilenet_distill.yaml
  
  # Distillation Hyperparameters
  distillation.alpha:
    values: [0.3, 0.5, 0.7, 0.9, 1]
    
  # Model Variants (Architectures)
  student_model.params:
    values:
      # MobileNetV2_Short_Thin2
      - {experiment_name: "MobileNetV2_Short_Thin2_Distill", version: "v2", v2_spec: [[3, 2], [3, 1], [6, 2], [6, 1], [12, 2], [12, 1], [18, 2], [18, 1], [24, 2], [24, 1]]}
      
      # MobileNetV2_Full_Thin1
      - {experiment_name: "MobileNetV2_Full_Thin1_Distill", version: "v2", v2_spec: [[3, 2], [4, 1], [6, 2], [6, 1], [8, 2], [8, 1], [10, 2], [10, 1], [10, 1], [10, 1], [10, 1], [10, 1], [12, 2], [12, 1]]}
      
      # MobileNetV2Exp_Halved_Thin4
      - {experiment_name: "MobileNetV2Exp_Halved_Thin4_Distill", version: "v2", v2_spec: [[3, 2], [3, 1, 3], [4, 2, 3], [5, 2, 3], [6, 2, 3], [7, 2, 3]]}
      
      # MobileNetV2_Short_Thin4
      - {experiment_name: "MobileNetV2_Short_Thin4_Distill", version: "v2", v2_spec: [[3, 2], [3, 1], [4, 2], [4, 1], [5, 2], [5, 1], [6, 2], [6, 1], [7, 2], [7, 1]]}

      # MobileNetV1_Halved_Thin3
      - {experiment_name: "MobileNetV1_Halved_Thin3_Distill", version: "v1", v1_spec: [[3, 2], [3, 1], [4, 2], [6, 2], [8, 2], [10, 2]]}
