project: "Week5_SqueezeNet"
entity: "c3-team4"
experiment_name: "SqueezeNet_Base"

data:
  train_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/train"
  test_dir: "/ghome/group04/mcv/datasets/C3/2425/MIT_small_train_1/test"
  img_size: 128  # SqueezeNet works well with moderate image sizes
  batch_size: 32
  num_workers: 4
  val_split: 0.5
  num_classes: 8

model:
  name: "SqueezeNetMini"
  params:
    # Default parameters
    stem_channels: 32
    fire_config:
      - [8, 16, 16]   # Fire1: 32 out
      - [8, 16, 16]   # Fire2: 32 out
      - [16, 32, 32]  # Fire3: 64 out
      - [16, 32, 32]  # Fire4: 64 out
      - [24, 48, 48]  # Fire5: 96 out
      - [24, 48, 48]  # Fire6: 96 out
    use_bypass: true
    dropout: 0.5

training:
  epochs: 200
  learning_rate: 0.001
  seed: 42
  optimizer: "adam"
  criterion: "crossentropy"
